// import localFont from "next/font/local";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { Ruwudu } from "next/font/google";

const poppins = Ruwudu({ subsets: ["latin"], weight: "700" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="container-fluid">
          <div className="row">
            <div className="col-md-3  vh-100 position-fixed  text-white p-0">
              <Sidebar />
            </div>

            {/* Right side   */}
            <div
              className="col-md-9 offset-md-3 p-0"
              style={{ overflowY: "auto", height: "100vh" }}
            >
              <div className="position-sticky top-0 bg-white z-index-1000">
                <Header />
              </div>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
